### ISSUE TITLE
Get endefector communication up and running

### ISSUE THREAD

**Issue by cantthinkofaname1029** [MST-MRDT/Robotic-Arm#32]
The endefector's data runs from motherboard through us to the endefector. Need to create code to pass the data along

**Comment by cantthinkofaname1029** [comment]
4.2 patched this in. Works successfully

**Comment by AlecBayliff** [comment]
Was this developed in the VMWare player?

On Fri, Feb 20, 2015 at 4:12 PM, Drue Satterfield <notifications@github.com>
wrote:

> 4.2 patched this in. Works successfully
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MST-MRDT/Robotic-Arm/issues/32#issuecomment-75329086>.
>



-- 
*Mars Rover Design Team* Telemetry and Controls Robotic Arm Project Lead
*Miners in Space* Member
*Institute of Electrical and Electronics Engineers *Program Manager

**Comment by cantthinkofaname1029** [comment]
Not developed but compiles successfully in it as well, after one modifies the include paths for the VM files

**Comment by AlecBayliff** [comment]
It needs to be developed for VMWare so that anyone running the VMWare
version can compile it. That's why we are using it.

**Comment by cantthinkofaname1029** [comment]
Well I'll push a version with the modified includes
